### ISSUE TITLE
Connection Reset - why :( 

### ISSUE THREAD

**Issue by kgnfth** [quantumcore/remote_hacker_probe#14] opened 2021-11-23 21:51 UTC
i am getting this error when a client connects

```
[INFO] New connection from : /REDACTED:65366
java.net.SocketException: Connection reset
        at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323)
        at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
        at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
        at java.base/java.net.Socket$SocketInputStream.read(Socket.java:976)
        at java.base/java.io.InputStream.read(InputStream.java:218)
        at rhp.Server.getInformation(Server.java:158)
        at rhp.Server$1.run(Server.java:267)
        at java.base/java.lang.Thread.run(Thread.java:831)
```

this is the settings i use

![Annotation 2021-11-23 214611](https://user-images.githubusercontent.com/73314940/143134506-07a39fcf-6a6e-4f50-8f5c-2b5305cc6f70.png)

```
java --version
java 16.0.2 2021-07-20
Java(TM) SE Runtime Environment (build 16.0.2+7-67)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.2+7-67, mixed mode, sharing)
```

**Comment by quantumcore** [comment] 2021-11-25 19:57
Try restarting the server.

**Comment by quantumcore** [comment] 2021-11-25 19:58
Oh I think I get it, Use Ipv4 address and check if it works.

**Comment by kgnfth** [comment] 2021-11-27 18:19
> Oh I think I get it, Use Ipv4 address and check if it works.

i already use my server ipv4, firewall is off btw

![image](https://user-images.githubusercontent.com/73314940/143701873-9ebc44f7-6db5-4af4-a7a3-6716acbb84f3.png)

**Comment by quantumcore** [comment] 2021-11-29 11:10
Somethings wrong with the client. Try rebuilding and checking. It's hard to tell what the problem is like this.

**Comment by kgnfth** [comment] 2021-12-02 21:58
this is what happens

**on my testing server**
1. i open Task Manager
2. i run probe.exe (probe client)
3. probe.exe is running and showing on taskmanager

**on my RHP server**
as soon as i run RHP, i get this error
```
[INFO] New connection from : /testingserver-ip:65366
java.net.SocketException: Connection reset
        at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323)
        at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
        at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
        at java.base/java.net.Socket$SocketInputStream.read(Socket.java:976)
        at java.base/java.io.InputStream.read(InputStream.java:218)
        at rhp.Server.getInformation(Server.java:158)
        at rhp.Server$1.run(Server.java:267)
        at java.base/java.lang.Thread.run(Thread.java:831)
```

and at the same time probe.exe from testing server gets killed 
that is the meaning of `Connection reset`

**Comment by quantumcore** [comment] 2021-12-03 15:28
Oh I just figured it out. The Client is getting an incorrect Wan IP address or failing to send the proper data.

The error is triggered here.
```java
  // Get WAN IP
			
			    Arrays.fill(buffer, (byte)0);
			    read = is.read(buffer); // <-- here!
			    String wanip = new String(buffer, 0, read);
```

check on the client machine if it can get the wan ipv4 address. Or try disconnecting it from the internet and trying locally for testing if you can. 

BTW are you on discord?

**Comment by kgnfth** [comment] 2021-12-03 21:01
i send you an email about my discord username

**Comment by kgnfth** [comment] 2021-12-03 22:42
correct me if i am wrong but if the clients is getting an wrong wan ip, then i should not see a Connection reset from the console right ?
How do i check if it can get the wan ipv4
also i have over 20 clients and they all gets killed 
i send u an email for my dc username

**Comment by quantumcore** [comment] 2021-12-22 18:19
FINALLY I FIGURED OUT WHAT THE PROBLEM IS.

Gonna fix soon.

**Comment by kgnfth** [comment] 2021-12-22 19:27
> FINALLY I FIGURED OUT WHAT THE PROBLEM IS.
> 
> Gonna fix soon.

😍

**Comment by quantumcore** [comment] 2022-01-04 11:06
Alright the bug was due to the client side getting the WAN IP.
It used to get it's ip from `` bot.whatsmyipaddress.com`` but it's not online anymore. 
This crashed the program.

The bug was fixed but I found another, FTP Passwords were not being extracted. And that is also fixed now.
I will upload the new release as soon as I can. Then will close this issue.
Thank you for reporting!

**Comment by kgnfth** [comment] 2022-01-04 18:09
Alright, thank you very much for your time

**Comment by quantumcore** [comment] 2022-01-07 17:17
https://github.com/quantumcore/remote_hacker_probe/releases/tag/V.2.2

Thanks alot for reporting! You're awesome! :)

**Closed by quantumcore** 2022-01-07 17:17 UTC
